import os
from dotenv import load_dotenv

load_dotenv()

COMPUTER_VISION_KEY = os.getenv("AZURE_COMPUTER_VISION_KEY")
COMPUTER_VISION_ENDPOINT = os.getenv("AZURE_COMPUTER_VISION_ENDPOINT")
BLOB_CONNECTION_STRING = os.getenv("AZURE_BLOB_CONNECTION_STRING")
BLOB_CONTAINER_NAME = os.getenv("AZURE_BLOB_CONTAINER_NAME")
FACE_KEY = os.getenv("AZURE_FACE_KEY")
FACE_ENDPOINT = os.getenv("AZURE_FACE_ENDPOINT")
COMMUNICATION_CONNECTION_STRING = os.getenv("AZURE_COMMUNICATION_CONNECTION_STRING")
SENDER_EMAIL = os.getenv("AZURE_SENDER_EMAIL")
TRANSLATOR_KEY = os.getenv("AZURE_TRANSLATOR_KEY")
TRANSLATOR_REGION = os.getenv("AZURE_TRANSLATOR_REGION")